package sample.basics

import com.sahsenvar.kmapper.annotations.MapFrom

/**
 * BASICS 2 — declaring the mapping on the TARGET side with `@MapFrom`.
 *
 * Sometimes the domain class is the natural home for mapping knowledge (e.g. the wire model
 * is generated by another tool and you cannot annotate it). `@MapFrom(InvoiceRow::class)` on
 * the domain class generates the same extension ON THE SOURCE:
 *
 *     fun InvoiceRow.toInvoiceResult(): Result<Invoice>
 *
 * Same rails, same Result boundary — only the declaration site moves.
 */
data class InvoiceRow(
    val number: String,
    val totalCents: Long,
)

@MapFrom(InvoiceRow::class)
data class Invoice(
    val number: String,
    val totalCents: Long,
)

fun main() = runReverseMappingDemo()

/** Callable from [sample.GalleryRunner] and the file's own `main`. */
fun runReverseMappingDemo() {
    val invoice = InvoiceRow(number = "INV-2026-0042", totalCents = 129_900).toInvoiceResult().getOrThrow()
    println("mapped invoice -> $invoice")
}
