package com.sahsenvar.kmapper.annotations

/**
 * Generated by the kmap KSP processor for each @CollectionWrapper function.
 * Annotated onto a synthetic object in package `com.sahsenvar.kmapper.generated`.
 * BINARY retention lets consumers discover wrappers from dependency artifacts via
 * resolver.getDeclarationsFromPackage("com.sahsenvar.kmapper.generated").
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class CollectionWrapperDescriptor(
    /** Fully-qualified name of the target collection type (e.g. "kotlinx.collections.immutable.PersistentList"). */
    val forType: String,
    /** Fully-qualified name of the wrapper function (e.g. "com.example.asPersistentList"). */
    val wrapFunction: String
)
