name: Validate Gradle Wrapper

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validation:
    name: Validate wrapper
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
